Develop 2
h2ash/react_todo-app pull request #1
Opened 2019-07-26 15:58 UTC by h2ash

Demo: https://h2ash.github.io/react_todo-app/

2019-07-27 10:56 UTC, vpolets reviewed
якщо в вкладці  completed нажати clear all то відбувається цікавий баг відображаються активні . todo)

2019-07-27 10:57 UTC, vpolets requested changes
Поділи на компоненти

2019-07-27 10:57 UTC, vpolets commented on src/App.js
> +        <footer className="footer" style={{ display: 'block' }}>
це окремий компонент

2019-07-27 10:57 UTC, vpolets commented on src/App.js
> +        <section className="main" style={{ display: 'block' }}>
це окремий компонент

2019-07-27 10:57 UTC, vpolets commented on src/App.js
> +        <header className="header">
це окремий компонент

2019-07-29 16:33 UTC, vkryvytskyi approved these changes
Учти комментарии

2019-07-29 16:33 UTC, volodymyrkryvytskyy commented on src/App.js
> +      .filter(item => item.completed === false).length;
filter(item => !item.completed)

2019-07-29 16:33 UTC, volodymyrkryvytskyy commented on src/App.js
> +        .filter(item => item.completed === false);
filter(item => !item.completed)

2019-07-29 16:33 UTC, volodymyrkryvytskyy commented on src/App.js
> +
Лишняя пустая строка

2019-07-29 16:33 UTC, volodymyrkryvytskyy commented on src/components/FilterButtons.jsx
> +            // className="selected"
Комментарии удаляем

2019-07-29 16:33 UTC, volodymyrkryvytskyy commented on src/components/FilterButtons.jsx
> +            className={this.state.idOfA === 1 && 'selected'}
idOfA не лучшее название для переменной

2019-07-30 14:53 UTC, h2ash commented on src/components/FilterButtons.jsx
> +            className={this.state.idOfA === 1 && 'selected'}
Всё исправил.

2019-07-31 15:48 UTC, ValeriiKupyna commented on src/App.js
> +      console.log('editTodo is alive');
видали консоль

2019-07-31 15:48 UTC, ValeriiKupyna commented on src/App.js
> +        todoList: [...uncompletedTodos],
todoList: uncompletedTodos,

2019-07-31 15:48 UTC, ValeriiKupyna commented on src/App.js
> +          todoList: [...withoutRemovedItems],
todoList: withoutRemovedItems,

2019-07-31 15:48 UTC, ValeriiKupyna commented on src/App.js
> +        completed: !prevState.todoList.every(todo => todo.completed)
ти запускаєш в кожному циклі ще один новий новий цикл. цього легко позбутись якщо 
зберегти результат prevState.todoList.every(todo => todo.completed) до виклику  map і просто використати його тут

2019-08-02 11:08 UTC, vkryvytskyi approved these changes

2019-12-08 19:13 UTC, merged